apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: increase-vm-max-map-count
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: increase-vm-max-map-count
  template:
    metadata:
      labels:
        name: increase-vm-max-map-count
    spec:
      hostPID: true
      containers:
      - name: sysctl
        image: busybox
        command: ["sh", "-c", "sysctl -w vm.max_map_count=262144 && sleep 3600"]
        securityContext:
          privileged: true
      restartPolicy: Always
