replicaCount: 1

image:
  repository: bitnami/kafka
  tag: 3.6.1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9092

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 400m
    memory: 1Gi

zookeeper:
  enabled: false
  host: moussaada-zookeeper.default.svc.cluster.local
