replicaCount: 2

image:
  repository: ilyassoussi/moussaada-front
  tag: 1.0.0.preprod
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

env:
  SPRING_PROFILES_ACTIVE: kubernetes  

ingress:
  enabled: false
  host: moussaada.104.154.24.129.nip.io