replicaCount: 2

image:
  repository: docker.hub/ilyassoussi/moussaada-front
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

env:
  SPRING_PROFILES_ACTIVE: kubernetes  