replicaCount: 1

image:
  repository: ilyassoussi/moussaada-front
  tag: 1.0.1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

env:
  SPRING_PROFILES_ACTIVE: kubernetes  

ingress:
  enabled: true
  host: moussaada.34.30.83.254.nip.io