# Activer le ServiceMonitor automatique (important)
prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}

grafana:
  adminPassword: admin
  service:
    type: ClusterIP
  ingress:
    enabled: false

# Node Exporter
prometheus-node-exporter:
  enabled: true

# Alertmanager (désactivable si tu veux)
alertmanager:
  enabled: true
