replicaCount: 1

image:
  repository: consul
  tag: "1.15"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8500

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
